### ISSUE TITLE
DOCUMENTATION

### ISSUE THREAD

**Issue by blitzdose** [TheDevTec/TheAPI#12]
Hi,

your API is great. It *should* make it easy to implement stuff like GUIs but with practically zero documentation it's tough to use. Your examples are not nearly enough to start coding with your API. I also noticed that the Discord invitation is not valid anymore so there is no place where I could ask for help.

I already mentioned the missing documentation a year ago as a spigot.mc review but nothing has changed since then. Even just using Javadoc would help because at the moment I have to dig through your code just to know what methods there are and try to guess what exactly they do. My current problem is "How can I add a ClickListener on an Iiem in a GUI?" The demo only shows how to add an Item.

**Comment by Straikerinos** [comment]
Hi, sorry for the complications, I have a lot on my plate at the moment.
The discord link should be fixed. Alternatively: https://discord.gg/APwYKQRxby
You can contact me directly there and I'll give you tips on the API if you do.
Otherwise regarding the GUI and ItemGUI, Click Event is implemented directly in ItemGUI as an abstract method.

```java
GUI gui = new GUI("title here", GUI.LINES_6);
gui.setItem(0, new ItemGUI(ItemMaker.of(XMaterial.STONE).displayName("&7Stone!").build()) {
	
	@Override
	public void onClick(Player player, HolderGUI gui, ClickType click) {
		player.sendMessage("You clicked on stone.");
		gui.close(player);
	}
});
gui.open(target)```

**Comment by blitzdose** [comment]
Hi, thanks for the clarification. Don't worry take your time. But would be nice if a documentation would be prioritized. For developers its just a nightmare otherwise :)

**Comment by blitzdose** [comment]
Still looks really amazing, but still not usable at all. You NEED documentation. Digging through code or asking on Discord is no documentation.
